name: 'ArgoCD Config Updater'
description: 'Updates ArgoCD config files by updating mutable git refs and Docker tag, and promoting values between environments'
author: 'Apollo GraphQL'

# Define your inputs here.
inputs:
  files:
    description: 'Glob pattern for files to search'
    required: true

  github-token:
    description: 'GitHub token to read refs and trees; only needed if update-git-refs is set'
  
  update-git-refs:
    description: 'Process trackMutableRef instructions'
    default: 'false'
  
  update-docker-tags-for-artifact-registry-repository:
    description: 'Process trackMutableTag instructions; must be set to a string of the form `projects/PROJECT/locations/LOCATION/repositories/REPOSITORY`'
  
  update-promoted-values:
    description: 'Process promote instructions'
    default: 'false'
  
  promotion-target-regexp:
    description: 'Only process promote instructions for targets matching this regexp'
  
  parallelism:
    description: 'How many files to process in parallel'
    default: '1'

outputs:
  sanitized-promotion-target-regexp:
    description: 'DEPRECATED: The promotion-target-regexp input with special characters changed to underscores; appropriate for constructing a branch name'

  suggested-promotion-branch-name:
    description: 'A combination of the promotion-target-regexp and files inputs with special characters changed to underscores; appropriate for constructing a branch name'

runs:
  using: node20
  main: dist/index.js
