name: 'ArgoCD Config Updater'
description: 'Updates ArgoCD config files by updating mutable git refs and Docker tag, and promoting values between environments'
author: 'Apollo GraphQL'

# Define your inputs here.
inputs:
  api-cache:
    description: 'Path to a file used to cache API calls (works well with actions/cache)'

  files:
    description: 'Glob pattern for files to search'
    required: true

  github-token:
    description: 'GitHub token to read refs and trees; only needed if update-git-refs is set'

  update-git-refs:
    description: 'Update tracked gitConfig.ref fields'
    default: 'false'

  update-docker-tags:
    description: 'Update tracked dockerImage.tag fields'
    default: 'false'

  artifact-registry-repository:
    description: 'If update-docker-tags or generate-promoted-commits-markdown is set, must be set to a string of the form `projects/PROJECT/locations/LOCATION/repositories/REPOSITORY`'

  update-docker-tags-for-artifact-registry-repository:
    description: 'DEPRECATED: equivalent to setting artifact-registry-repository and update-docker-tags'

  update-promoted-values:
    description: 'Process promote instructions'
    default: 'false'

  promotion-target-regexp:
    description: 'Only process promote instructions for targets matching this regexp'

  parallelism:
    description: 'How many files to process in parallel'
    default: '1'
  
  generate-promoted-commits-markdown:
    description: 'Generates the promoted-commits-markdown output'
    default: 'false'

outputs:
  suggested-promotion-branch-name:
    description: 'A combination of the promotion-target-regexp and files inputs with special characters changed to underscores; appropriate for constructing a branch name'
  
  promoted-commits-markdown:
    description: 'Markdown describing the commits being promoted, if update-promoted-values and generate-promoted-commits-markdown are set.'

runs:
  using: node20
  main: dist/index.js
